"""add_openrouter_key_to_users

Revision ID: cf7db7844895
Revises: d0db556e97f7
Create Date: 2026-03-19 20:27:06.162429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7db7844895'
down_revision: Union[str, None] = 'd0db556e97f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'model_choice',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'gemini'::character varying"))
    op.add_column('users', sa.Column('encrypted_openrouter_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_openrouter_key')
    op.alter_column('chats', 'model_choice',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'gemini'::character varying"))
    # ### end Alembic commands ###
