"""add model_choice to chats

Revision ID: d0db556e97f7
Revises: 0a522d4ef99d
Create Date: 2026-03-02 10:59:28.498886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0db556e97f7'
down_revision: Union[str, None] = '0a522d4ef99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('model_choice', sa.String(length=50), server_default='gemini', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'model_choice')
    # ### end Alembic commands ###
